# Generated by Django 5.0.6 on 2024-06-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('historia', models.TextField()),
                ('periodoActualizacion', models.IntegerField()),
                ('ultimaActualizacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Maridaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('premium', models.BooleanField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siguiendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFin', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('porcentajeComposicion', models.IntegerField()),
                ('tipoUva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.tipouva')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('añada', models.IntegerField()),
                ('imagenEtiqueta', models.CharField(max_length=200)),
                ('notaDeCataBodega', models.CharField(max_length=300)),
                ('precioARS', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.bodega')),
                ('maridaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.maridaje')),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.varietal')),
            ],
            options={
                'unique_together': {('nombre', 'añada')},
            },
        ),
        migrations.CreateModel(
            name='Enofilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('imagenPerfil', models.CharField(max_length=30)),
                ('siguiendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.siguiendo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.usuario')),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.vino')),
            ],
        ),
    ]
