# Generated by Django 5.0.6 on 2024-05-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maridaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('porcentajeComposicion', models.IntegerField()),
                ('tipoUva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.tipouva'))
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('historia', models.CharField(max_length=50)),
                ('periodoActualizacion', models.IntegerField()),
                ('ultimaActualizacion', models.DateTimeField())
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('añada', models.CharField(max_length=100)),
                ('ImagenEtiqueta', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=50)),
                ('notaDeCataBodega', models.CharField(max_length=100)),
                ('precioARS', models.IntegerField()),
                ('maridaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.maridaje')),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.varietal')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.bodega'))
            ],
        ),
    ]
