# Generated by Django 5.0.6 on 2024-05-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maridaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionVitinicola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.TextField()),
                ('porcComposicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
                ('historia', models.CharField(max_length=50)),
                ('perActualizacion', models.IntegerField()),
                ('coordenadasUbi', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.regionvitinicola')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('añada', models.CharField(max_length=100)),
                ('ImagenEstiqueta', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=50)),
                ('notaDeCata', models.CharField(max_length=100)),
                ('precioARS', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.bodega')),
                ('maridaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.maridaje')),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.varietal')),
            ],
        ),
    ]
