# Generated by Django 5.0.6 on 2024-05-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacionVino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='maridaje',
            name='tipoVino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.tipouva'),
            preserve_default=False,
        ),
    ]
