# Generated by Django 5.0.6 on 2024-05-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacionVino', '0002_tipouva_maridaje_tipovino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maridaje',
            name='tipoVino',
        ),
        migrations.AddField(
            model_name='varietal',
            name='tipoVino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actualizacionVino.tipouva'),
            preserve_default=False,
        ),
    ]
